import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated automatically from the docs/ folder structure.
// Each NN-section/ folder becomes a category (label/position from its
// _category_.json); each NN-topic.md becomes an item (title from its H1,
// order from the NN- filename prefix). No per-file frontmatter required.
const sidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
